version: "3"

services:
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_DATABASE_VOLUME:-./data/mongo}/db:/data/db
    networks:
      - mongo-compose-network

  identity_database:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ${POSTGRES_DATABASE_VOLUME:-./data/postgres}/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mongo-compose-network
  
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - mongo-compose-network
  
networks:
  mongo-compose-network:
    driver: bridge
