services:
  reverse-proxy:
    volumes:
      # Map the certificats into the container
      - .docker/certs:/etc/certs:ro

  api:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Api/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-api:${VERSION:-latest}'

  web:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Web/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-web:${VERSION:-latest}'
