version: '3.4'

services:

  mysql-data-test:
    environment:
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306
    volumes:
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

  budgeting-api-functional-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      MongoDatabaseSettings__ConnectionString: mongodb://mongo
      MongoDatabaseSettings__Database: holefeeder
      HolefeederDatabaseSettings__ConnectionString: Server=mysql-data-test;Port=3306;User Id=test_user;Password=test_password;AllowPublicKeyRetrieval=True;SslMode=none;Database=holefeeder_test;
    ports:
      - "5105:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-funtional-test-results.xml
        - --logger
        - html;LogFileName=/tests/budgeting-funtional-test-results.html
        - --logger
        - junit;LogFileName=/tests/budgeting-funtional-test-results.junit.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"

  budgeting-api-unit-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5112:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-unit-test-results.xml
        - --logger
        - html;LogFileName=/tests/budgeting-unit-test-results.html
        - --logger
        - junit;LogFileName=/tests/budgeting-unit-test-results.junit.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"

  object-store-api-functional-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ObjectStoreDatabaseSettings__ConnectionString: Server=mysql-data-test;Port=3306;User Id=test_user;Password=test_password;AllowPublicKeyRetrieval=True;SslMode=none;Database=object_store_test;
    ports:
      - "5106:80"
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/object-store-funtional-test-results.xml
      - --logger
      - html;LogFileName=/tests/object-store-funtional-test-results.html
      - --logger
      - junit;LogFileName=/tests/object-store-funtional-test-results.junit.xml
      - --results-directory
      - /tests
      - --collect
      - "XPlat Code Coverage"

  object-store-api-unit-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5113:80"
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/object-store-unit-test-results.xml
      - --logger
      - html;LogFileName=/tests/object-store-unit-test-results.html
      - --logger
      - junit;LogFileName=/tests/object-store-unit-test-results.junit.xml
      - --results-directory
      - /tests
      - --collect
      - "XPlat Code Coverage"
