version: '3.4'

services:

  gateway-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - SEQ_Url=http://seq
    ports:
      - '5200:80'
  
  budgeting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=mongodb://holefeederApi:holefeederApi@mongo/?authSource=holefeeder
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - '5100:80'

  object-store-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=mongodb://holefeederApi:holefeederApi@mongo/?authSource=holefeeder
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - '5102:80'

  legacy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MongoDB__ConnectionString=mongodb://holefeederApi:holefeederApi@mongo/?authSource=holefeeder
      - MongoDB__DatabaseName=holefeeder
    ports:
      - '5101:80'

  webspa:
    environment:
      - NGX_API_URL=http://localhost:5200
      - NGX_REDIRECT_URL=http://localhost
      - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - '80:80'

networks:
  default:
    external:
      name: backend-network
      