version: '3.4'

services:

  gateway-web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
      SEQ_Url: ${SEQ_URL}
    ports:
      - '5200:80'
  
  budgeting-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      SEQ_Url: ${SEQ_URL}
      HolefeederDatabaseSettings:ConnectionString: Server=${MYSQL_SERVER};Port=${MYSQL_PORT};User Id=${MYSQL_USER};Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=none;Database=holefeeder;
    ports:
      - '5100:80'

  object-store-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      SEQ_Url: ${SEQ_URL}
      ObjectStoreDatabaseSettings__ConnectionString: Server=${MYSQL_SERVER};Port=${MYSQL_PORT};User Id=${MYSQL_USER};Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=none;Database=object_store;
    ports:
      - '5102:80'

  webspa:
    environment:
      NGX_API_URL: http://localhost:5200
      NGX_REDIRECT_URL: http://localhost
      NGINX_PORT: 80
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - '80:80'

networks:
  default:
    external: true
    name: backend-network
      