version: "3.7"

services:
  mysql-data-test:
    image: mariadb:10.5.13
    container_name: mysql-data-test

  api-functional-tests:
    image: api-functional-tests
    container_name: api-functional-tests
    build:
      context: .
      dockerfile: ./src/Api/Holefeeder.Api/Dockerfile
      target: functionaltests
    depends_on:
      - mysql-data-test
    volumes:
      - ./tests-results:/TestResults

  api-unit-tests:
    image: api-unit-tests
    container_name: api-unit-tests
    build:
      context: .
      dockerfile: ./src/Api/Holefeeder.Api/Dockerfile
      target: unittests
    volumes:
      - ./tests-results/:/TestResults
