version: '3.4'

services:

  budgeting-api-functional-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      MongoDatabaseSettings__ConnectionString: mongodb://holefeeder:drifterapps123@mongo/?authSource=holefeeder
      MongoDatabaseSettings__Database: holefeeder
      HolefeederDatabaseSettings__ConnectionString: Server=${MYSQL_SERVER};Port=${MYSQL_PORT};User Id=${MYSQL_USER};Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=none;Database=holefeeder_int;
    ports:
      - "5105:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-funtional-test-results.xml
        - --logger
        - html;LogFileName=/tests/budgeting-funtional-test-results.html
        - --logger
        - junit;LogFileName=/tests/budgeting-funtional-test-results.junit.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"

  budgeting-api-unit-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5112:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-unit-test-results.xml
        - --logger
        - html;LogFileName=/tests/budgeting-unit-test-results.html
        - --logger
        - junit;LogFileName=/tests/budgeting-unit-test-results.junit.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"

  object-store-api-functional-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ObjectStoreDatabaseSettings__ConnectionString: Server=${MYSQL_SERVER};Port=${MYSQL_PORT};User Id=${MYSQL_USER};Password=${MYSQL_PASSWORD};AllowPublicKeyRetrieval=True;SslMode=none;Database=object_store_int;
    ports:
      - "5106:80"
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/object-store-funtional-test-results.xml
      - --logger
      - html;LogFileName=/tests/object-store-funtional-test-results.html
      - --logger
      - junit;LogFileName=/tests/object-store-funtional-test-results.junit.xml
      - --results-directory
      - /tests
      - --collect
      - "XPlat Code Coverage"

  object-store-api-unit-test:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
    ports:
      - "5113:80"
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/object-store-unit-test-results.xml
      - --logger
      - html;LogFileName=/tests/object-store-unit-test-results.html
      - --logger
      - junit;LogFileName=/tests/object-store-unit-test-results.junit.xml
      - --results-directory
      - /tests
      - --collect
      - "XPlat Code Coverage"

networks:
  default:
    external:
      name: backend-network
      