apiVersion: skaffold/v3
kind: Config
metadata:
  name: holefeeder
build:
  local:
    useBuildkit: true # We use BuildKit
  tagPolicy:
    envTemplate:
      template: "{{if .VERSION}}{{.VERSION}}{{else}}99.99.99{{end}}"
  artifacts:
    - image: holefeeder/holefeeder-web
      context: .
      docker:
        dockerfile: src/Holefeeder.Web/Dockerfile
        buildArgs:
          BUILD_VERSION: "{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}"
        noCache: false
    - image: holefeeder/holefeeder-api
      context: .
      docker:
        dockerfile: src/Holefeeder.Api/Dockerfile
        buildArgs:
          BUILD_VERSION: "{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}"
        noCache: false
profiles:
  - name: dev
    activation:
      - kubeContext: k3d-dev
    build:
      artifacts:
        - image: holefeeder/holefeeder-web
          context: .
          docker:
            dockerfile: src/Holefeeder.Web/Dockerfile
            target: debugger
            buildArgs:
              BUILD_VERSION: "{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}"
            noCache: false
        - image: holefeeder/holefeeder-api
          context: .
          docker:
            dockerfile: src/Holefeeder.Api/Dockerfile
            target: debugger
            buildArgs:
              BUILD_VERSION: "{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}"
            noCache: false
    manifests:
      kustomize:
        paths:
          - "kubernetes/dev"
  - name: prd
    manifests:
      kustomize:
        paths:
          - "kubernetes/prd"
