apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: holefeeder
build:
  tagPolicy:
    envTemplate:
      template: '{{.VERSION}}'
  artifacts:
  - image: ghcr.io/drifterapps/holefeeder/holefeeder-web
    context: .
    docker:
      dockerfile: src/Web/Holefeeder.Web/Dockerfile
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
  - image: ghcr.io/drifterapps/holefeeder/holefeeder-budgeting-api
    context: .
    docker:
      dockerfile: src/Services/Budgeting/Budgeting.API/Dockerfile
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
  - image: ghcr.io/drifterapps/holefeeder/holefeeder-object-store-api
    context: .
    docker:
      dockerfile: src/Services/ObjectStore/ObjectStore.API/Dockerfile
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
profiles:
  - name: cicd
    build:
      local:
        push: false
    deploy: {}
  - name: dev
    activation:
      - kubeContext: minikube
    patches:
      - op: replace
        path: /build/artifacts/0/docker/buildArgs/BUILD_VERSION
        value: '99.99.99'
      - op: replace
        path: /build/artifacts/1/docker/buildArgs/BUILD_VERSION
        value: '99.99.99'
      - op: replace
        path: /build/artifacts/2/docker/buildArgs/BUILD_VERSION
        value: '99.99.99'
    deploy:
      kustomize:
        paths: ["kubernetes/dev"]
  - name: stg
    deploy:
      kustomize:
        paths: ["kubernetes/stg"]
  - name: prd
    deploy:
      kustomize:
        paths: ["kubernetes/prd"]
