apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: holefeeder
build:
  tagPolicy:
    envTemplate:
      template: '{{.VERSION}}'
  artifacts:
  - image: holefeeder/holefeeder-gateway-web
    context: .
    docker:
      dockerfile: src/ApiGateways/Web.Gateway/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
  - image: holefeeder/holefeeder-web
    context: .
    docker:
      dockerfile: src/Web/Holefeeder.Web/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
  - image: holefeeder/holefeeder-budgeting-api
    context: .
    docker:
      dockerfile: src/Services/Budgeting/Budgeting.API/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
  - image: holefeeder/holefeeder-object-store-api
    context: .
    docker:
      dockerfile: src/Services/ObjectStore/ObjectStore.API/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{.ASSEMBLY_VERSION}}'
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    # patches:
    #   - op: replace
    #     path: /build/artifacts/0/docker/buildArgs/BUILD_VERSION
    #     value: '99.99.99'
    #   - op: replace
    #     path: /build/artifacts/1/docker/buildArgs/BUILD_VERSION
    #     value: '99.99.99'
    #   - op: replace
    #     path: /build/artifacts/2/docker/buildArgs/BUILD_VERSION
    #     value: '99.99.99'
    #   - op: replace
    #     path: /build/artifacts/3/docker/buildArgs/BUILD_VERSION
    #     value: '99.99.99'
    deploy:
      kustomize:
        paths: ["kubernetes/dev"]
  - name: prd
    deploy:
      kustomize:
        paths: ["kubernetes/prd"]
