apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: holefeeder
build:
  tagPolicy:
    envTemplate:
      template: '{{if .VERSION}}{{.VERSION}}{{else}}99.99.99{{end}}'
  artifacts:
  - image: holefeeder/holefeeder-gateway-web
    context: .
    docker:
      dockerfile: src/ApiGateways/Web.Gateway/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
  - image: holefeeder/holefeeder-web
    context: .
    docker:
      dockerfile: src/Web/Holefeeder.Web/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
  - image: holefeeder/holefeeder-budgeting-api
    context: .
    docker:
      dockerfile: src/Services/Budgeting/Budgeting.API/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
  - image: holefeeder/holefeeder-object-store-api
    context: .
    docker:
      dockerfile: src/Services/ObjectStore/ObjectStore.API/Dockerfile
      target: final
      buildArgs:
        BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
profiles:
  - name: dev
    activation:
      - kubeContext: docker-desktop
    deploy:
      kustomize:
        paths: ["kubernetes/dev"]
  - name: prd
    deploy:
      kustomize:
        paths: ["kubernetes/prd"]
