apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: holefeeder
build:
  tagPolicy:
    envTemplate:
      template: '{{if .VERSION}}{{.VERSION}}{{else}}99.99.99{{end}}'
  artifacts:
    - image: holefeeder/holefeeder-web
      context: .
      docker:
        dockerfile: src/Web/Holefeeder.Web/Dockerfile
        target: final
        buildArgs:
          BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
    - image: holefeeder/holefeeder-api
      context: .
      docker:
        dockerfile: src/Api/Holefeeder.Api/Dockerfile
        target: final
        buildArgs:
          BUILD_VERSION: '{{if .ASSEMBLY_VERSION}}{{.ASSEMBLY_VERSION}}{{else}}99.99.99{{end}}'
profiles:
  - name: dev-docker
    activation:
      - kubeContext: docker-desktop
    deploy:
      kustomize:
        paths: [ "kubernetes/dev" ]
  - name: dev-k3d
    activation:
      - kubeContext: k3d-*
    deploy:
      kustomize:
        paths: [ "kubernetes/dev" ]
  - name: prd
    deploy:
      kustomize:
        paths: [ "kubernetes/prd" ]
