apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
      tier: backend
  template:
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+
            - name: HolefeederDatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: BUDGETING_CONNECTION_STRING
            - name: ObjectStoreDatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: OBJECT_STORE_CONNECTION_STRING
            - name: AzureAdB2C__ClientId
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: AZURE_CLIENT_ID
