apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeting
spec:
  selector:
    matchLabels:
      app: budgeting
      tier: backend
  template:
    spec:
      containers:
        - name: budgeting
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SEQ_Url
            value: http://seq-prd
          - name: ASPNETCORE_URLS
            value: http://+
          - name: HolefeederDatabaseSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: holefeeder-secrets
                key: BUDGETING_CONNECTION_STRING
