apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      tier: backend
  template:
    spec:
      containers:
        - name: gateway
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SEQ_Url
            value: http://seq.default
          - name: ASPNETCORE_URLS
            value: http://+
          - name: GlobalConfiguration__Hosts__BudgetingUrl
            value: http://budgeting-prd
          - name: GlobalConfiguration__Hosts__ObjectStoreUrl
            value: http://object-store-prd
