- op: replace
  path: /spec/routes/0/match
  value: Host(`holefeeder.drifterapps.app`) && PathPrefix(`/gateway`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`holefeeder.drifterapps.app`)
- op: replace
  path: /spec/routes/2/match
  value: Host(`adminer.drifterapps.app`)
- op: replace
  path: /spec/routes/3/match
  value: Host(`seq.drifterapps.app`)
- op: add
  path: /spec/tls
  value: { secretName: holefeeder.drifterapps.app-tls }
