apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
nameSuffix: -prd
namespace: holefeeder-prd
patchesJson6902:
- target:
   version: v1
   kind: Namespace
   name: holefeeder
  path: namespace-patch.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ui
  path: ingress_patch.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: api
  path: ingress_patch.yaml
patchesStrategicMerge:
- budgeting.env.yaml
- gateway.env.yaml
- object-store.env.yaml
- ui.env.yaml
secretGenerator:
- name: holefeeder-secrets
  behavior: create
  envs:
  - .env.secrets
