apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

namespace: holefeeder

resources:
  - certificates.yaml

patchesStrategicMerge:
  - api.env.yaml
  - ui.env.yaml

patchesJson6902:
  - target:
      group: traefik.containo.us
      version: v1alpha1
      kind: IngressRoute
      name: holefeeder
    path: ingress.patch.yaml

secretGenerator:
  - name: holefeeder-secrets
    behavior: create
    envs:
      - .env.secrets
  - name: dockerconfigjson-github-com
    behavior: create
    envs:
      - .env.token

generatorOptions:
  disableNameSuffixHash: true
