apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: holefeeder
  path: ingress_patch.yaml
namePrefix: holefeeder-prd-
secretGenerator:
- name: budgeting
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder_user;Password=drifterapps123;AllowPublicKeyRetrieval=True;Database=budgeting_stg;
- name: object-store
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder_user;Password=drifterapps123;AllowPublicKeyRetrieval=True;Database=object_store_stg;
configMapGenerator:
- name: config-env
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Production
  - NGX_API_URL=https://holefeeder.drifterapps.app
  - NGX_REDIRECT_URL=https://holefeeder.drifterapps.app
