apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      tier: frontend
  template:
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
        - name: ui
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
            value: Microsoft.AspNetCore.SpaProxy
          - name: ASPNETCORE_URLS
            value: http://+
          - name: Api__Url
            value: http://api-prd
          - name: AngularSettings__RedirectUrl
            value: https://holefeeder.drifterapps.app
