version: '3.1'

services:

  seq:
    container_name: seq
    restart: unless-stopped
    image: datalust/seq:latest
    ports:
    - 5341:80
    volumes:
    - seq-data:/data
    environment:
    - DEFAULT_HOST=seq.drifterapps.com
    - VIRTUAL_HOST=seq.drifterapps.com
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=seq.drifterapps.com
    - LETSENCRYPT_EMAIL=info@drifterapps.com
    - ACCEPT_EULA=Y
  
networks:
  default:
    external:
      name: shared-proxy

volumes:
  seq-data: