apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: holefeeder
spec:
  selector:
    matchLabels:
      app: api
  template:
    spec:
      containers:
        - name: api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ConnectionStrings__BudgetingConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: BUDGETING_CONNECTION_STRING
            - name: AzureAdB2C__ClientId
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: AZURE_CLIENT_ID
