apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: holefeeder
  labels:
    app: api
spec:
  ports:
    - name: api-debugger
      port: 22
      targetPort: 22
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: holefeeder
spec:
  selector:
    matchLabels:
      app: api
  template:
    spec:
      containers:
        - name: api
          ports:
            - containerPort: 22
              name: api-debugger
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ConnectionStrings__BudgetingConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: BUDGETING_CONNECTION_STRING
            - name: AzureAdB2C__ClientId
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: AZURE_CLIENT_ID
