apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
      tier: backend
  template:
    spec:
      containers:
        - name: api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ConnectionStrings__HolefeederConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: EF_BUDGETING_CONNECTION_STRING
            - name: ConnectionStrings__ObjectStoreConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: EF_OBJECT_STORE_CONNECTION_STRING
            - name: HolefeederDatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: BUDGETING_CONNECTION_STRING
            - name: ObjectStoreDatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: OBJECT_STORE_CONNECTION_STRING
            - name: AzureAdB2C__ClientId
              valueFrom:
                secretKeyRef:
                  name: holefeeder-secrets
                  key: AZURE_CLIENT_ID
