apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql
  namespace: holefeeder
spec:
  entryPoints:
    - mysql
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mysql
          namespace: holefeeder
          port: 3306
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: api
  namespace: holefeeder
spec:
  entryPoints:
    - debugger
  routes:
    - match: HostSNI(`*`)
      services:
        - name: api
          namespace: holefeeder
          port: 22
