- op: replace
  path: /spec/rules/0/host
  value: holefeeder.127.0.0.1.nip.io
- op: replace
  path: /spec/rules/1/host
  value: adminer.127.0.0.1.nip.io
- op: replace
  path: /spec/rules/2/host
  value: seq.127.0.0.1.nip.io
