- op: replace
  path: /spec/routes/0/match
  value: Host(`holefeeder.lvh.me`) && PathPrefix(`/gateway`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`holefeeder.lvh.me`)
- op: replace
  path: /spec/routes/2/match
  value: Host(`adminer.lvh.me`)
- op: replace
  path: /spec/routes/3/match
  value: Host(`seq.lvh.me`)
