apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

patchesStrategicMerge:
  - api.env.yaml
  - seq.deployment.yaml
  - ui.env.yaml

secretGenerator:
  - name: holefeeder-secrets
    namespace: holefeeder
    behavior: create
    envs:
      - .secrets/.env.secrets

generatorOptions:
  disableNameSuffixHash: true
