apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

nameSuffix: -dev

namespace: holefeeder

patchesStrategicMerge:
- budgeting.env.yaml
- gateway.env.yaml
- object-store.env.yaml
- ui.env.yaml

secretGenerator:
- name: holefeeder-secrets
  behavior: create
  envs:
  - .env.secrets
