apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
namePrefix: holefeeder-dev-
secretGenerator:
- name: budgeting
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder_user;Password=drifterapps123;AllowPublicKeyRetrieval=True;Database=budgeting_dev;
- name: object-store
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder_user;Password=drifterapps123;AllowPublicKeyRetrieval=True;Database=object_store_dev;
configMapGenerator:
- name: config-env
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Development
  - NGX_API_URL=https://holefeeder.test
  - NGX_REDIRECT_URL=https://holefeeder.test
