apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
nameSuffix: -dev
namespace: holefeeder-dev
patchesJson6902:
- target:
   version: v1
   kind: Namespace
   name: holefeeder
  path: namespace-patch.yaml
secretGenerator:
- name: holefeeder-secrets
  behavior: replace
  envs:
  - .env.secrets
configMapGenerator:
- name: config-env
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Development
  - NGX_API_URL=https://holefeeder.test
  - NGX_REDIRECT_URL=https://holefeeder.test
  - SEQ_URL=http://seq.default
  - BUDGETING_URL=http://budgeting-dev
  - OBJECT_STORE_URL=http://object-store-dev