apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # - ../cert-manager
  - ../base

patchesStrategicMerge:
  - api.env.yaml
  - mysql.deployment.yaml
  - seq.deployment.yaml
  - ui.env.yaml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: holefeeder
    path: ingress.patch.yaml

secretGenerator:
  - name: holefeeder-secrets
    namespace: holefeeder
    behavior: create
    envs:
      - .secrets/.env.secrets
  - name: holefeeder-ca
    namespace: holefeeder
    files:
      - .secrets/tls.crt
      - .secrets/tls.key
    type: "kubernetes.io/tls"

generatorOptions:
  disableNameSuffixHash: true
