apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
nameSuffix: -dev
namespace: holefeeder-dev
patchesJson6902:
- target:
   version: v1
   kind: Namespace
   name: holefeeder
  path: namespace-patch.yaml
patchesStrategicMerge:
- budgeting.env.yaml
- gateway.env.yaml
- object-store.env.yaml
- ui.env.yaml
secretGenerator:
- name: holefeeder-secrets
  behavior: create
  envs:
  - .env.secrets
