apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      tier: frontend
  template:
    spec:
      containers:
        - name: ui
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
            value: Microsoft.AspNetCore.SpaProxy
          - name: ASPNETCORE_URLS
            value: http://+
          - name: Budgeting__Url
            value: http://budgeting-dev
          - name: ObjectStore__Url
            value: http://object-store-dev
          - name: AngularSettings__RedirectUrl
            value: https://holefeeder.test
