apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: holefeeder
  labels:
    app: adminer
spec:
  ports:
    - name: adminer
      port: 80
      targetPort: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: holefeeder
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - image: adminer
          name: adminer
          ports:
            - containerPort: 8080
              name: adminer
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 50m
