apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: holefeeder
  labels:
    app: api
spec:
  ports:
    - name: api
      port: 80
      targetPort: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: holefeeder
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: holefeeder/holefeeder-api
          name: api
          ports:
            - containerPort: 80
              name: api
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 750m
          startupProbe:
            httpGet:
              path: /health/startup
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            successThreshold: 3
