apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: holefeeder
  labels:
    app: api
spec:
  ports:
    - name: api
      port: 80
      targetPort: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: holefeeder
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: holefeeder/holefeeder-api
          name: api
          ports:
            - containerPort: 80
              name: api
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 150m
