apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gateway-stripprefix
  namespace: holefeeder
spec:
  stripPrefix:
    prefixes:
      - /gateway
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limit
  namespace: holefeeder
spec:
  buffering:
    maxRequestBodyBytes: 31457280
    memRequestBodyBytes: 31457280
    maxResponseBodyBytes: 31457280
    memResponseBodyBytes: 31457280
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: holefeeder
  namespace: holefeeder
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(``)
      services:
        - name: api
          port: 80
      middlewares:
        - name: gateway-stripprefix
          namespace: holefeeder
    - kind: Rule
      match: Host(``)
      services:
        - name: ui
          port: 80
    - kind: Rule
      match: Host(``)
      services:
        - name: adminer
          port: 80
    - kind: Rule
      match: Host(``)
      services:
        - name: seq
          port: 80
