apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gateway-stripprefix
  namespace: holefeeder
spec:
  stripPrefix:
    prefixes:
      - /gateway
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limit
  namespace: holefeeder
spec:
  buffering:
    maxRequestBodyBytes: 31457280
    memRequestBodyBytes: 31457280
    maxResponseBodyBytes: 31457280
    memResponseBodyBytes: 31457280
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: holefeeder
  namespace: holefeeder
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: holefeeder-gateway-stripprefix@kubernetescrd, holefeeder-limit@kubernetescrd
spec:
  rules:
    - host: holefeeder.127.0.0.1.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ui
                port:
                  number: 80
          - pathType: Prefix
            path: /gateway
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: adminer.127.0.0.1.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: adminer
                port:
                  number: 80
    - host: seq.127.0.0.1.nip.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: seq
                port:
                  number: 80
  tls:
    - secretName: holefeeder-ca
