apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - web-ui.yaml
  - api-budgeting.yaml
  - api-object-store.yaml
  - ingress.yaml

configMapGenerator:
- name: config-env
- name: ui-config
  files:
  - templates/default.conf.template
