apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- budgeting.deployment.yaml
- budgeting.service.yaml
- gateway.deployment.yaml
- gateway.ingress.yaml
- gateway.service.yaml
- namespace.yaml
- object-store.deployment.yaml
- object-store.service.yaml
- ui.deployment.yaml
- ui.ingress.yaml
- ui.service.yaml
configMapGenerator:
- name: ui-config
  files:
  - templates/default.conf.template
