apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store
  labels:
    app: object-store
spec:
  selector:
    matchLabels:
      app: object-store
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: object-store
        tier: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: holefeeder/holefeeder-object-store-api
        name: object-store
        ports:
        - containerPort: 80
          name: object-store
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 250m
