apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: holefeeder
  labels:
    app: ui
spec:
  ports:
    - name: ui
      port: 80
      targetPort: 80
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: holefeeder
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - image: holefeeder/holefeeder-web
          name: ui
          ports:
            - containerPort: 80
              name: ui
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 150m
