http:
  routers:
    traefik:
      rule: "Host(`traefik.localtest.me`)"
      service: "api@internal"
      tls:
        certResolver: acme_certresolver
        domains:
          - main: "localtest.me"
            sans:
              - "*.localtest.me"

tls:
  certificates:
    - certFile: "/etc/certs/localtest.me+4.pem"
      keyFile: "/etc/certs/localtest.me+4-key.pem"
