global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  sql:
    address: ":3306"
  whoami:
    address: ":5011"

certificatesResolvers:
  acme_certresolver:
    acme:
      email: patrick@drifterapps.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      keyType: "RSA4096"
      # Note: Since we're using mkcert, the CA server is not used,
      # but the structure is maintained for consistency.
