version: '3.4'

services:

  nosql-data-test:
    ports:
      - "27017:27017"

  budgeting-api-functional-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data-test}
      - HolefeederDatabaseSettings__Database=holefeeder_integration_test
    ports:
      - "5105:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-funtional-test-results.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"

  budgeting-api-unit-test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5112:80"
    entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/budgeting-unit-test-results.xml
        - --results-directory
        - /tests
        - --collect
        - "XPlat Code Coverage"
