# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:

  gateway-web:
    volumes:
      - ~/.vsdbg:/dbg:rw
  
  budgeting-api:
    volumes:
      - ~/.vsdbg:/dbg:rw

  object-store-api:
    volumes:
      - ~/.vsdbg:/dbg:rw

  legacy-api:
    volumes:
      - ~/.vsdbg:/dbg:rw

  webspa:
    volumes:
      - ~/.vsdbg:/dbg:rw
