version: '3.4'

services:
  
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
  
  nosql-data:
    ports:
      - "27017:27017"
    volumes:
      - holefeeder-nosql-data:/data/db

  gateway-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SEQ_Url=http://seq:5341
    ports:
      - "5200:80"
  
  budgeting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - "5100:80"

  legacy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MongoDB__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - MongoDB__DatabaseName=holefeeder
    ports:
      - "5101:80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederWeb__ApiUrl=http://${HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP:-localhost}:5200
      - HolefeederWeb__RedirectUrl=http://${HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP:-localhost}
    ports:
      - "80:80"

volumes:
  holefeeder-nosql-data:
    external: false
