version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:80'
  
  nosql-data:
    ports:
      - 27017
    volumes:
      - holefeeder-nosql-data:/data/db

  gateway-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SEQ_Url=http://seq:5341
    ports:
      - 80
  
  budgeting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - 80

  object-store-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - 80

  legacy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MongoDB__ConnectionString=mongodb://${MONGO_HOLEFEEDERAPI_USER}:${MONGO_HOLEFEEDERAPI_PASSWORD}@mongodb:27017/?authSource=${MONGO_DATABASE_AUTH}
      - MongoDB__DatabaseName=${MONGO_DATABASE_NAME}
      - MongoDB__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - MongoDB__DatabaseName=holefeeder
    ports:
      - 80

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederWeb__ApiUrl=https://${HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP:-localhost}
      - HolefeederWeb__RedirectUrl=https://${HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP:-localhost}
      - DEFAULT_HOST=holefeeder${ENVIRONMENT_PREFIX}.drifterapps.com
      - VIRTUAL_HOST=holefeeder${ENVIRONMENT_PREFIX}.drifterapps.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=holefeeder${ENVIRONMENT_PREFIX}.drifterapps.com
      - LETSENCRYPT_EMAIL=info@drifterapps.com
    ports:
      - 80

volumes:
  holefeeder-nosql-data:
    external: false
