version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:80'
  
  nosql-data:
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
    ports:
      - '27017:27017'
    volumes:
      - holefeeder-nosql-data:/data/db
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  gateway-web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - SEQ_Url=http://seq:5341
    ports:
      - '5200:80'
  
  budgeting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - '5100:80'

  object-store-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HolefeederDatabaseSettings__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - HolefeederDatabaseSettings__Database=holefeeder
    ports:
      - '5102:80'

  legacy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MongoDB__ConnectionString=${HOLEFEEDER_MONGODB:-mongodb://nosql-data}
      - MongoDB__DatabaseName=holefeeder
    ports:
      - '5101:80'

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://+
      - HolefeederWeb__ApiUrl=http://localhost:5200
      - HolefeederWeb__RedirectUrl=http://localhost
    ports:
      - '80:80'

volumes:
  holefeeder-nosql-data:
    external: false
