apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: holefeeder-stg-
bases:
- ../base
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ui
  path: ingress_patch.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: api
  path: ingress_patch.yaml
secretGenerator:
- name: budgeting
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder-stg-user;Password=g_PMJEkm8r2-gGZ3Vq.MNp@e;AllowPublicKeyRetrieval=True;Database=budgeting_stg;
- name: object-store
  literals:
  - connection-string=Server=mysql;Port=3306;User Id=holefeeder-stg-user;Password=g_PMJEkm8r2-gGZ3Vq.MNp@e;AllowPublicKeyRetrieval=True;Database=object_store_stg;
configMapGenerator:
- name: config-env
  behavior: merge
  literals:
  - ASPNETCORE_ENVIRONMENT=Staging
  - NGX_API_URL=https://holefeeder-staging.drifterapps.app
  - NGX_REDIRECT_URL=https://holefeeder-staging.drifterapps.app
