name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main]
    types: [completed]

env:
  DOCKER_REGISTRY: ghcr.io/drifterapps/holefeeder

jobs:

  get-version:
    name: Set version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.majorMinorPatch }}
      assembly-version: ${{ steps.gitversion.outputs.semVer }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Disable workflow commands
        run: |
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml

      - name: Display GitVersion outputs
        run: |
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: Enable workflow commands
        run: |
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

  deploy:
    name: Deploy to production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
      ENVIRONMENT: Production
    environment:
      name: production

    steps:

    - uses: actions/checkout@v2

    - uses: yokawasa/action-setup-kube-tools@v0.8.0
      with:
        kubectl: '1.22.2'
        kustomize: '4.4.0'
        skaffold: '1.32.0'

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Create .env.secrets file
      run: |
        printf "BUDGETING_CONNECTION_STRING=Server=mysql.default;Port=3306;User Id=${{ secrets.MYSQL_USER }};Password=${{ secrets.MYSQL_PASSWORD }};AllowPublicKeyRetrieval=True;Database=budgeting_prd;
        OBJECT_STORE_CONNECTION_STRING=Server=mysql.default;Port=3306;User Id=${{ secrets.MYSQL_USER }};Password=${{ secrets.MYSQL_PASSWORD }};AllowPublicKeyRetrieval=True;Database=object_store_prd;
        " > $GITHUB_WORKSPACE/kubernetes/prd/.env.secrets

    - name: Set image tags
      run: |
        cd $GITHUB_WORKSPACE/kubernetes/prd
        kustomize edit set image ghcr.io/drifterapps/holefeeder/holefeeder-gateway-web=ghcr.io/drifterapps/holefeeder/holefeeder-gateway-web:${{ env.VERSION }}
        kustomize edit set image ghcr.io/drifterapps/holefeeder/holefeeder-budgeting-api=ghcr.io/drifterapps/holefeeder/holefeeder-budgeting-api:${{ env.VERSION }}
        kustomize edit set image ghcr.io/drifterapps/holefeeder/holefeeder-object-store-api=ghcr.io/drifterapps/holefeeder/holefeeder-object-store-api:${{ env.VERSION }}
        kustomize edit set image ghcr.io/drifterapps/holefeeder/holefeeder-web=ghcr.io/drifterapps/holefeeder/holefeeder-web:${{ env.VERSION }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-21-3-do-0-tor1-1634177939904

    - name: Build deployment
      run: kustomize build $GITHUB_WORKSPACE/kubernetes/prd

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -k $GITHUB_WORKSPACE/kubernetes/prd
