name: holefeeder ci/cd

on:
  pull_request:
    branches:
    - main
    - master

    paths-ignore:
    - 'proxy/**'
    - 'docs/**'

env:
  DOCKER_REGISTRY: docker.pkg.github.com/drifterapps/holefeeder

jobs:
  set-version:
    name: build version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build-version.outputs.version }}

    steps:
    - name: set version
      id: build-version
      run: echo "##[set-output name=version;]$(date +'%y.%m').${{github.run_number}}" 

  build:
    name: build, test and package
    runs-on: ubuntu-latest
    needs: set-version
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
      BUILD_CONTEXT: ./src

    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"DrifterApps_Holefeeder" /o:"drifterapps" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          <your clean build command>
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"




    - uses: actions/checkout@v2

    - name: docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.DOCKER_REGISTRY }} -u DrifterApps --password-stdin

    - run: docker-compose pull

    - name: build containers
      run: docker-compose build --build-arg holefeeder_version=${{ env.VERSION }}

    - name: budget api unit tests
      if: ${{ success() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run budgeting-api-unit-test

    - name: budgeting api functional tests
      if: ${{ success() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run budgeting-api-functional-test

    - name: object-store api unit tests
      if: ${{ success() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-unit-test

    - name: object-store api functional tests
      if: ${{ success() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-functional-test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: ${{ success() }}
      with:
        check_name: unit-test-results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: tests-results/*.junit.xml

    - name: setup .NET core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v1
      if: ${{ always() }}
      with:
        dotnet-version: 5.0.101

    - name: report generator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.3
      if: ${{ always() }}
      with:
        reports: 'tests-results/*/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        sourcedirs: 'src/'
        reporttypes: 'HtmlInline;Cobertura'
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: upload coverage report artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: coverage-report
        path: coveragereport

    - name: push containers
      run: docker-compose push

    - name: upload deployable files
      uses: actions/upload-artifact@v2
      with:
        name: deployables
        path: |
          docker-compose.yml
          docker-compose.prod.yml
          mongo/mongod.conf
          mongo/initdb.d/create-app-user.sh

  staging:
    name: deploy to staging
    runs-on: ubuntu-latest
    needs:
    - set-version
    - build
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
      ENVIRONMENT: Staging
      ENVIRONMENT_PREFIX: -staging
      HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP: holefeeder-staging.drifterapps.com
    environment:
      name: staging

    steps:
    - uses: actions/checkout@v2

    - name: download deployables artifacts
      uses: actions/download-artifact@v2
      with:
        name: deployables
        path: ./artifacts/.

    - name: create environment file
      run: |
        printf "VERSION=${{ env.VERSION }}
        DOCKER_REGISTRY=${{ env.DOCKER_REGISTRY }}
        ENVIRONMENT=${{ env.ENVIRONMENT }}
        ENVIRONMENT_PREFIX=${{ env.ENVIRONMENT_PREFIX }}
        HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP=${{ env.HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP }}
        MONGO_REPLICA_SET_NAME=${{ secrets.MONGO_REPLICA_SET_NAME }}
        MONGO_CONNECTION_STRING=mongodb://${{ secrets.MONGODB_HOLEFEEDERAPI_USER }}:${{ secrets.MONGODB_HOLEFEEDERAPI_PASSWORD }}@nosql-data/?authSource=${{ secrets.MONGO_DATABASE_NAME }}
        MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGODB_ROOT_USER }}
        MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGODB_ROOT_PASSWORD }}
        MONGO_INITDB_USERNAME=${{ secrets.MONGODB_HOLEFEEDERAPI_USER }}
        MONGO_INITDB_PASSWORD=${{ secrets.MONGODB_HOLEFEEDERAPI_PASSWORD }}
        MONGO_INITDB_DATABASE=${{ secrets.MONGO_DATABASE_NAME }}
        MONGO_DATABASE_VOLUME=./mongo
        SEQ_ApiKey=${{ secrets.SEQ_APIKEY }}
        " > .env
      working-directory: ./artifacts

    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_WEB_SERVER }}
        username: ${{ secrets.PROD_WEB_SERVER_USER }}
        port: ${{ secrets.PROD_WEB_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "artifacts/docker-compose.yml,artifacts/docker-compose.prod.yml,artifacts/.env,artifacts/mongo/mongod.conf,artifacts/mongo/initdb.d/create-app-user.sh"
        target: holefeeder-staging
        strip_components: 1
   
    - name: starting containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_WEB_SERVER }}
        username: ${{ secrets.PROD_WEB_SERVER_USER }}
        port: ${{ secrets.PROD_WEB_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ~/holefeeder-staging
          echo github registry login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u DrifterApps --password-stdin
          echo pull containers
          docker-compose pull
          echo start containers
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

  deploy:
    name: deploy to production
    runs-on: ubuntu-latest
    needs:
    - set-version
    - staging
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
      ENVIRONMENT: Production
      HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP: holefeeder.drifterapps.com
    environment:
      name: production

    steps:
    - uses: actions/checkout@v2


    - name: download deployables artifacts
      uses: actions/download-artifact@v2
      with:
        name: deployables
        path: ./artifacts/.

    - name: create environment file
      run: |
        printf "VERSION=${{ env.VERSION }}
        DOCKER_REGISTRY=${{ env.DOCKER_REGISTRY }}
        ENVIRONMENT=${{ env.ENVIRONMENT }}
        ENVIRONMENT_PREFIX=${{ env.ENVIRONMENT_PREFIX }}
        HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP=${{ env.HOLEFEEDER_EXTERNAL_DNS_NAME_OR_IP }}
        MONGO_REPLICA_SET_NAME=${{ secrets.MONGO_REPLICA_SET_NAME }}
        MONGO_CONNECTION_STRING=mongodb://${{ secrets.MONGODB_HOLEFEEDERAPI_USER }}:${{ secrets.MONGODB_HOLEFEEDERAPI_PASSWORD }}@nosql-data/?authSource=${{ secrets.MONGO_DATABASE_NAME }}
        MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGODB_ROOT_USER }}
        MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGODB_ROOT_PASSWORD }}
        MONGO_INITDB_USERNAME=${{ secrets.MONGODB_HOLEFEEDERAPI_USER }}
        MONGO_INITDB_PASSWORD=${{ secrets.MONGODB_HOLEFEEDERAPI_PASSWORD }}
        MONGO_INITDB_DATABASE=${{ secrets.MONGO_DATABASE_NAME }}
        MONGO_DATABASE_VOLUME=./mongo
        SEQ_ApiKey=${{ secrets.SEQ_APIKEY }}
        " > .env
      working-directory: ./artifacts

    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PROD_WEB_SERVER }}
        username: ${{ secrets.PROD_WEB_SERVER_USER }}
        port: ${{ secrets.PROD_WEB_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "artifacts/docker-compose.yml,artifacts/docker-compose.prod.yml,artifacts/.env,artifacts/mongo/mongod.conf,artifacts/mongo/initdb.d/create-app-user.sh"
        target: holefeeder
        strip_components: 1
   
    - name: starting containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_WEB_SERVER }}
        username: ${{ secrets.PROD_WEB_SERVER_USER }}
        port: ${{ secrets.PROD_WEB_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd ~/holefeeder
          echo github registry login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u DrifterApps --password-stdin
          echo pull containers
          docker-compose pull
          echo start containers
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          echo stop staging
          cd ~/holefeeder-staging
          docker-compose down
          echo cleanup previous images
          docker image prune -f
