name: Continous deployment PROXY

on:
  push:
    branches:
      - master
      - release/*
    paths:
      - .github/workflows/**
      - proxy/**
env:
  TEST: test

jobs:
  Deploy-Proxy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.PROD_WEB_SERVER }}
        USERNAME: ${{ secrets.PROD_WEB_SERVER_USER }}
        PORT: ${{ secrets.PROD_WEB_SERVER_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "proxy/.env,proxy/docker-compose-multiple-networks.yml,proxy/docker-compose.yml,proxy/start.sh,proxy/conf.d/realip.conf,proxy/conf.d/servertokens.conf,proxy/conf.d/uploadsize.conf"
        target: "holefeeder-proxy"
        strip_components: 1

    - name: Starting proxy
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.PROD_WEB_SERVER }}
        USERNAME: ${{ secrets.PROD_WEB_SERVER_USER }}
        PORT: ${{ secrets.PROD_WEB_SERVER_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        script: |
          echo Docker login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u DrifterApps --password-stdin
          cd holefeeder-proxy
          echo Start container
          chmod +x start.sh
          ./start.sh -e .env
          echo Cleanup previous images
          docker image prune -f