name: Continous deployment PROXY

on:
  push:
    branches:
      - master
      - release/*
    paths:
      - proxy/**
env:
  TEST: test

jobs:
  Deploy-Proxy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.PROD_WEB_SERVER }}
        USERNAME: ${{ secrets.PROD_WEB_SERVER_USER }}
        PORT: ${{ secrets.PROD_WEB_SERVER_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "./proxy/docker-compose.yml ./proxy/docker-compose-multiple-networks.yml ./proxy/.env ./proxy/start.sh ./proxy/conf.d"
        target: "/holefeeder-proxy"

    # - name: Executing remote  command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: ${{ secrets.PORT }}
    #     KEY: ${{ secrets.SSHKEY }}
    #     script: cat /opt/app/README.md