name: Continous deployment

on:
  push:
    branches: [ release/* ]

jobs:
  package-budget-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Install dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet publish --no-restore --output ./publish/DrifterApps.Holefeeder.ServicesHosts.BudgetApi ./src/DrifterApps.Holefeeder.ServicesHosts.BudgetApi/DrifterApps.Holefeeder.ServicesHosts.BudgetApi.csproj

    - name: Package
      run: |
        docker build --pull 
        cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u DrifterApps --password-stdin
        docker tag IMAGE_ID docker.pkg.github.com/drifterapps/repository-name/IMAGE_NAME:VERSION
        docker push docker.pkg.github.com/drifterapps/repository-name/IMAGE_NAME:VERSION

  package-budget-ui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./src/DrifterApps.Holefeeder.Presentations.UI

    - name: Build
      run: npm build -- --aot=true --outputHashing=all --outputPath=../../publish/DrifterApps.Holefeeder.Presentations.UI --sourceMap=false
      working-directory: ./src/DrifterApps.Holefeeder.Presentations.UI

    - name: Package
      run: |
        docker build --pull 
        cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u DrifterApps --password-stdin
        docker tag IMAGE_ID docker.pkg.github.com/drifterapps/repository-name/IMAGE_NAME:BETA
        docker push docker.pkg.github.com/drifterapps/repository-name/IMAGE_NAME:BETA
