name: Continous integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build containers
      run: docker-compose build
      working-directory: ./src

    - name: test
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml up budgeting-api-unit-test budgeting-api-functional-test object-store-api-unit-test object-store-api-functional-test
      working-directory: ./src

    - name: report-generator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.5.7
      with:
        reports: 'src/tests-results/*/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coveragereport
