name: continuous integration

on:
  pull_request:
    branches:
    - main
    - master
    - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker-compose pull
      working-directory: ./src

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: build containers
      run: docker-compose build
      working-directory: ./src

    - name: budget api unit tests
      if: ${{ success() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run budgeting-api-unit-test
      working-directory: ./src

    - name: budgeting api functional tests
      if: ${{ always() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run budgeting-api-functional-test
      working-directory: ./src

    - name: object-store api unit tests
      if: ${{ always() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-unit-test
      working-directory: ./src

    - name: object-store api functional tests
      if: ${{ always() }}
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-functional-test
      working-directory: ./src

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: ${{ always() }}
      with:
        check_name: unit-test-results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: src/tests-results/*.junit.xml

    - name: setup .NET core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: report generator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.3
      with:
        reports: 'src/tests-results/*/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        sourcedirs: 'src/'
        reporttypes: 'HtmlInline;Cobertura'
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: upload coverage report artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coveragereport
