name: Continous Integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src

    - name: Test
      run: dotnet test --no-restore --no-build --collect:"XPlat Code Coverage"
      working-directory: ./src

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.5.6
      with:
        reports: '**/*Tests/TestResults/*/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        assemblyfilters: '+*'
        classfilters: '+*'
        filefilters: '+*'
        verbosity: 'Verbose'
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coveragereport
