name: Continous integration

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RESULTS_PATH: src/tests-results

    steps:
    - uses: actions/checkout@v2
    - name: build containers
      run: docker-compose build
      working-directory: ./src

    - name: test
      run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml up budgeting-api-unit-test budgeting-api-functional-test object-store-api-unit-test object-store-api-functional-test
      working-directory: ./src

    # - name: functional test budgeting api
    #   run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run budgeting-api-functional-test
    #   working-directory: ./src

    # - name: unit test object-store api
    #   run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-unit-test
    #   working-directory: ./src

    # - name: functional test object-store api
    #   run: docker-compose -f docker-compose-tests.yml -f docker-compose-tests.override.yml run object-store-api-functional-test
    #   working-directory: ./src

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: src/tests-results/*.junit.xml

    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: report-generator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.3
      with:
        reports: 'src/tests-results/*/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        sourcedirs: 'src/'
        reporttypes: 'HtmlInline;Cobertura'
        tag: '${{ github.run_number }}_${{ github.run_id }}'

    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coveragereport
