name: linter

on:
  push:
    branches: [main]

  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v3

  check_changes:
    uses: patmoreau/workflow-config/.github/workflows/check-changes-action.yml@main
    with:
      file_patterns: ${{ vars.LINTER_CODE_FILE_PATTERNS }}

  typescript:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.code_was_changed == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install dependencies
        working-directory: src/Web/Holefeeder.Web/ClientApp
        run: yarn install

      - name: Lint code with ESLint
        id: lint
        working-directory: src/Web/Holefeeder.Web/ClientApp
        run: yarn lint --format node_modules/eslint-formatter-pretty > ./eslint-report.md

      - name: Print ESLint report
        if: always()
        working-directory: src/Web/Holefeeder.Web/ClientApp
        run: cat ./eslint-report.md

      - name: Upload ESLint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ESLint report
          path: src/Web/Holefeeder.Web/ClientApp/eslint-report.md

      - name: Check for errors
        if: ${{ steps.lint.outcome != 'success' }}
        run: echo "::error::eslint found issues in the code. Please fix them."

  csharp:
    runs-on: ubuntu-latest
    needs: check_changes
    if: ${{ needs.check_changes.outputs.code_was_changed == 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Lint C# files with dotnet format
        id: lint
        run: dotnet format --severity error --verbosity diagnostic --report ./linter-report || true

      - name: Save report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-format-report
          path: ./linter-report/*

      - name: Check for errors
        if: ${{ steps.lint.outcome != 'success' }}
        run: echo "::error::dotnet format found issues in the code. Please fix them."

  create_check:
    needs: [check_changes, csharp, typescript]
    uses: patmoreau/workflow-config/.github/workflows/create-check.yml@main
    if: always() && needs.check_changes.result == 'success'
    with:
      code_was_changed: ${{ needs.check_changes.outputs.code_was_changed }}
      check_name: 'linter-completed'
      check_result: ${{ needs.csharp.result }}
