name: Mutation Tests

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:
jobs:
  stryker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure .NET Installed
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Stryker.NET global tool
        run: dotnet tool install --global dotnet-stryker

      - name: Restore packages
        run: dotnet restore

      - name: Run Mutation tests
        if: github.event_name == 'pull_request'
        run: dotnet stryker --with-baseline:${{ github.event.pull_request.base.ref }} --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ github.event.pull_request.head.ref }}

      - name: Run Mutation tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet stryker --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ github.ref }}
